titles: [Bin Wang](https://timedotcom.files.wordpress.com/2015/09/googles-new-logo-5078286822539264-2-hp.gif)
title: Bin Wang
description: USC
show_downloads: false
#google_analytics:
theme: jekyll-theme-dinky